name: CI

on:
  push:
  schedule:
    - cron: "0 6 * * 1"

jobs:
  style:
    runs-on: ubuntu-latest
    container: crystallang/crystal
    steps:
      - uses: actions/checkout@v2
      - name: Format
        run: crystal tool format --check
      - name: Lint
        uses: crystal-ameba/github-action@v0.2.12

  test:
    strategy:
      fail-fast: false
      matrix:
        stable: [true]
        crystal:
          - 1.1.0
          - 1.0.0
          - 0.36.1
        include:
          - stable: false
            crystal: nightly
    name: "crystal: ${{ matrix.crystal }}, stable: ${{ matrix.stable }}"
    runs-on: ubuntu-latest
    continue-on-error: ${{ !matrix.stable }}
    steps:
      - uses: oprypin/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}
      - uses: actions/checkout@v2
      - name: Run tests
        run: crystal spec -v --error-trace

  publish:
    if: contains('refs/tags', github.ref)
    runs-on: ubuntu-latest
    container: crystallang/crystal:latest
    steps:
      - uses: actions/checkout@v2
      - run: shards install --ignore-crystal-version
      - name: Run `crystal docs`
        run: crystal docs
      - name: Publish to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: docs
          build_dir: docs
          commit_message: "docs: update for ${{ github.ref }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
