name: CI

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        experimental: [false]
        crystal:
          - latest
          - 1.0.0
          - 0.36.1
        include:
          - experimental: true
            crystal: nightly
    name: "crystal: ${{ matrix.crystal }}, unstable: ${{ matrix.experimental }}"
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    container: crystallang/crystal:${{ matrix.crystal }}-alpine
    steps:
    - uses: actions/checkout@v2
    - name: Format
      run: crystal tool format --check
    - name: Run tests
      run: crystal spec -v --error-trace
